project:
  type: manuscript
  output-dir: output

execute:
  echo: false
  warning: false
  output: asis

crossref: false
fig-prefix: figure   # (default is "Figure")
tbl-prefix: table    # (default is "Table")
appendix-title: "App."
appendix-delim: ":"
