project:
  type: book
  output-dir: output

book:
  title: "Green Belt"
  subtitle: "Lean / Six Sigma"
  author:
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      roles: "drafted the manuscript"
      affiliations:
        - name: Amsterdam University of Applied Sciences
          department: Business and Economics
          address: Fraijlemaborg 133
          city: Amsterdam
          country: The Netherlands
          postal-code: 1102 CV
          url: www.amsterdamaus.com
          ror: 00y2z2s03
        - name: Vlerick Business School
          address: Reep 1
          city: Ghent
          country: Belgium
          postal-code: 9000
          url: www.vlerick.com
          ror: 056t38c37

  date: "4/11/2024"
  date-format: "DD/MM/YYYY"
 
  chapters:
    - index.qmd
    - 1_definitie_fase.qmd
    - 2_measure_fase.qmd
    - 3_analyse_fase.qmd
    - 4_improve_fase.qmd
    - 5_control_fase.qmd

  appendices:
    - 6_kosten.qmd
    - 7_studiebelasting.qmd
    - 8_dataset.qmd

format-links: [pdf, docx]

format:
  pdf:
    papersize: a4
    mermaid:
      theme: neutral
    cite-method: citeproc
    toc: true
    lof: true
    lot: true
  html: 
    title-block-banner: true
    number-sections: true
    date-modified: "5/2/2024"
    toc: true
  #  comments:
  #    hypothesis: true
  docx: default

execute:
  echo: false
  warning: false
  output: asis

crossref: false
fig-prefix: figure   # (default is "Figure")
tbl-prefix: table    # (default is "Table")
appendix-title: "App."
appendix-delim: ":"
