project:
  type: website
  output-dir: output

book:
  title: "Green Belt"
  subtitle: "Lean / Six Sigma"
  downloads: [pdf,docx]
  search: true
  repo-url: https://github.com/jan-ru/lss_greenbelt
  author:
    - name: "Jan-Ru Muller"
      orcid: 0000-0003-1689-0557
      email: janru.muller@edu.vlerick.com
      roles: "drafted the manuscript"
      affiliations:
        - name: Amsterdam University of Applied Sciences
          department: Business and Economics
          address: Fraijlemaborg 133
          city: Amsterdam
          country: The Netherlands
          postal-code: 1102 CV
          url: www.amsterdamaus.com
          ror: 00y2z2s03
        - name: Vlerick Business School
          address: Reep 1
          city: Ghent
          country: Belgium
          postal-code: 9000
          url: www.vlerick.com
          ror: 056t38c37

  date: "8/21/2024"
  date-format: "DD/MM/YYYY"
 
  chapters:
    - index.qmd
    - 1_definitie_fase.qmd
    - 2_measure_fase.qmd
    - 3_analyse_fase.qmd
    - 4_improve_fase.qmd
    - 5_control_fase.qmd

  appendices:
    - 6_kosten.qmd
    - 7_studiebelasting.qmd
    - 8_dataset.qmd

website:
  title: ""
  page-navigation: true
  navbar:
    collapse-below: lg
    background: light
    left:
      - text: Home
        href: index.qmd
      - text: Blackbelt
        menu:
          - text: Overview
            href: 2_blackbelt/index.qmd
          - text: "---"
          - text: Definition Phase
            href: 1_definitie_fase.qmd
          - text: Measure Phase
            href: 2_measure_fase.qmd
      - text: "Greenbelt"
        menu:
          - 3_analyse_fase.qmd
          - 4_improve_fase.qmd
          - 5_control_fase.qmd
          - 6_kosten.qmd

  sidebar:
    - id: blackbelt
      title: "Blackbelt"
      style: "floating"
      contents:
        - 2_blackbelt/index.qmd
        - 1_definitie_fase.qmd
        - 2_measure_fase.qmd
        - 3_analyse_fase.qmd
        - 4_improve_fase.qmd
        - 5_control_fase.qmd
        
    - id: bijlagen
      title: "Bijlagen"
      style: "floating"
      contents:
        - 6_kosten.qmd
        - 7_studiebelasting.qmd
        - 8_dataset.qmd

  page-footer:
    center:
      - text: "2024 Copyright (c) Hogeschool van Amsterdam"
    right:
      - icon: envelope-at-fill
        href: mailto:j.r.muller@hva.nl
      - icon: globe
        href: https://www.hva.nl/

format:
  pdf:
    papersize: a4
    mermaid:
      theme: neutral
    cite-method: citeproc
    toc: true
    toc-depth: 2
    lof: true
    lot: true
  html: 
    title-block-banner: false
    title-block-style: none
    number-sections: false
    date-modified: "8/21/2024"
    toc: true
    output-dir: output
  #  comments:
  #    hypothesis: true
  docx: default

execute:
  echo: false
  warning: false
  output: asis

crossref: false
fig-prefix: figure   # (default is "Figure")
tbl-prefix: table    # (default is "Table")
appendix-title: "App."
appendix-delim: ":"

bibliography: lss_references.bib
suppress-bibliography: true