project:
  type: book
  output-dir: output
Book:
  title: "Green Belt"
  subtitle: "Lean / Six Sigma"
  author: Jan-Ru Muller
  date: "4/11/2024"
  date-format: "DD/MM/YYYY"
  chapters:
    - index.qmd
    - 1_definitie_fase.qmd
    - 2_measure_fase.qmd
    - 3_analyse_fase.qmd
    - 4_improve_fase.qmd
    - 5_control_fase.qmd

  appendices:
    - 6_bijlagen.qmd

format:
  pdf:
    papersize: a4
    mermaid:
      theme: neutral
    cite-method: citeproc
    toc: true
    lof: true
    lot: true
  html: 
    title-block-banner: true
    number-sections: true
  #  comments:
  #    hypothesis: true
  docx: default

execute:
  echo: false
  warning: false
  output: asis

